---
title: "Ml_random"
author: "Nitin Khandare"
date: "June 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(randomForest)
library(caret)
library(class)
library(BBmisc)
hr = read.csv("E:/Term 2/Machine Learning/Datasets/HR Analytics.csv")


knitr::opts_chunk$set(echo = TRUE)
```


```{r}
hr$Attrition = as.factor(hr$Attrition)
set.seed(100)
hr_train = hr[sample(seq(1,nrow(hr)),(0.7*nrow(hr))),]

hr_test = hr[sample(seq(1,nrow(hr)),(0.3*nrow(hr))),]
```

```{r}
model_rf = randomForest(Attrition~.,data = hr_train)

pred_probs = predict(model_rf,hr_test, type = 'prob')


hr_test$pred_class = ifelse(pred_probs[,2]>0.5, 1, 0)

hr_test$pred_class = as.factor(hr_test$pred_class)
confusionMatrix(hr_test$pred_class,hr_test$Attrition,positive = '1')


```

### Random forest performance Evaluation
```{r}
model_rf = randomForest(Attrition~.,data = hr_train)

pred_probs = predict(model_rf,hr_test, type = 'prob')


hr_test$pred_class = ifelse(pred_probs[,2]>0.3, 1, 0)

hr_test$pred_class = as.factor(hr_test$pred_class)

confusionMatrix(hr_test$pred_class,hr_test$Attrition,positive = '1')
```

```{r}
### ROC curve 

library(ROCR)
library(pROC)

roc_rf = roc(hr_test$Attrition,pred_probs[,2])
plot(roc_rf)




```


```{r}
x$thresholds
x$sensitivities


table(hr_test$Attrition)
```




```{r}

hr = read.csv("E:/Term 2/Machine Learning/Datasets/HR Analytics.csv")

## Covert categorical columns to numerical columns
dummy_obj = dummyVars(~., data=hr %>% select(-Over18))
hr_new = data.frame(predict(dummy_obj, newdata = hr %>% select(-Over18)))

## Normalizing
hr_norm = normalize(hr_new, method='range', range = c(0,1))
set.seed(100)


hr_train = hr_norm[1:(0.7*nrow(hr)),]

hr_test = hr_norm[1:(0.7*nrow(hr)+1):nrow(hr),]
```


```{r}
pred_probs_knn = knn(hr_train %>% select(-Attrition),
                      hr_test %>% select(-Attrition),
                      cl= as.factor(hr_train$Attrition),
                      k=10,prob = T)

probs = data.frame(prob=attr(pred_probs_knn,'prob'),
                   class = pred_probs_knn)

probs[probs['class']==0,'prob']=1-
  probs[probs['class']==0,'prob']

roc_knn = roc(as.factor(hr_test$Attrition),probs$prob)

## her is the comparison between ROC_RandomForest and ROC_KNN
{{plot(roc_rf)
  lines(roc_knn, col='red')
  }}

```


```{r}

library(prediction)
library(pROC)
library(ROCR)
library(class)

auc(roc_rf)
auc(roc_knn)

pred_obj = prediction(pred_probs[,2], as.factor(hr_test$Attrition))

cost.perf = performance(pred_obj,'cost')

pred_obj@cutoffs[[1]][which.min(cost.perf@y.values[[1]])]

hr_test$new_class = as.factor(ifelse(pred_probs[,2]>0.43,1,0))

confusionMatrix(hr_test$new_class,as.factor(hr_train$Attrition),positive = '1')


```

```{r}
histogram(pred_probs[pred_probs[,2]>0.5,2])
```



## probablity calibration
```{r}
library(caret)
mushroom = read.csv("E:/Term 2/Machine Learning/Datasets/mushroom_full.csv")

df = mushroom

set.seed(100)

train = df[1:(0.7*nrow(df)),]
test = df[(0.7*nrow(df)+1):nrow(df),]

train = df[sample(seq(1,nrow(df)),(0.7*nrow(df))),]

test = df[sample(seq(1,nrow(df)),(0.3*nrow(df))),]

df_rf = randomForest(class~.,data=train)

pred_probs = as.data.frame(predict(df_rf, test, type = 'prob'))

View(pred_probs)
colnames(pred_probs)

pred_class1 = ifelse(pred_probs[,2]>0.5,"POISONOUS","EDIBLE")



confusionMatrix(pred_class1, test$class)



histogram(pred_probs[pred_probs[,2]>0.5,2])
```


```{r}

test$prob_pois = pred_probs[,2]

x_vals = c()
y_vals = c()

start_bin = 0

end_end = 
  
  
for(i in seq(0,1,0.05)){
  start_bin = i
  end_bin = i + 0.05
  x_vals = c(x_vals,(start_bin+end_bin)/2)

  df_subset = test}  
  
  


df_subset = test %>% filter(prob_pois>0.2 & prob_pois<0.3)
nrow(df_subset %>% filter(class=="POISONOUS"))/nrow(df_subset)


```


```{r}
hr = read.csv("E:/Term 2/Machine Learning/Datasets/HR Analytics.csv")

df = hr
df$class = as.factor(df$Atrrition)
df = df %>% select(-Attrition)
set.seed(100)
train = df[sample(seq(1,nrow(df)),(0.7*nrow(df))),]
test = df[sample(seq(1,nrow(df),(0.3*nrow(df)))),]



```

```{r}
library(caret)
train_probs = as.data.frame(predict(df_rf, train, type = 'prob'))

train_probs$class = train$class
colnames(train_probs) = c('prob_0','prob_1','class')
calib_model = glm(class~prob_1, data=train_probs,family = binomial)

test_probs = as.data.frame(predict(df_rf, test, type = 'prob'))
colnames(test_probs) = c("prob_0","prob_1")

test_probs$prob_1_new = predict(calib_model, test_probs, type='response')

test_probs$pred_class = as.factor(ifelse(test_probs$prob_1>0.5,1,0))

test_probs$pred_class_new = as.factor(ifelse(test_probs$prob_1_new>0.5,1,0))

confusionMatrix(test_probs$pred_class_new,test$class,positive = '1')


```
```{r}
### updated Threshould
library(pROC)
library(ROCR)



```

